/* SteelTrace matrix data — Client (supply-chain segments) + Stakeholder (buyer personas).
   Plain JS global so it can load before the React/Babel app. */
(function () {
  // CLIENT MATRIX — ordered melt -> end product (left to right along the supply chain)
  const SEGMENTS = [
    {
      code: "MFG",
      name: "Manufacturers & Material Suppliers",
      short: "Manufacturers",
      who: "Steel mills, pipe manufacturers, coating companies, clad layers and other material suppliers that produce pipeline components & generate critical production data.",
      stage: "Source",
      needs: [
        "Standardized digital data exchange with project stakeholders",
        "Less effort compiling MRBs and customer documentation",
        "Integration with existing production / MES systems",
        "Recognition for quality & on-time delivery",
      ],
      challenges: [
        "Manufacturing data stored in internal MES & production systems",
        "Manual certificate & documentation creation per customer",
        "Limited integration with downstream contractors",
        "Significant effort compiling Manufacturing Record Books",
      ],
      value: [
        "SteelTrace sits as a data layer above internal production systems",
        "Standardized digital data exchange with project stakeholders",
        "Material certs & manufacturing records flow into the SMR automatically",
        "One standardized exchange channel across multiple operator customers",
        "Verified traceability, melt to end product, visible to operators",
      ],
      content: [
        "Value for Manufacturers & Suppliers",
        "Mill, Pipe & Coating Data Integration",
        "Materials Traceability: Melt to End Product",
        "MES / ERP Connector Documentation",
      ],
    },
    {
      code: "WLD",
      name: "Welding Contractors",
      short: "Welding",
      who: "Pipeline welding contractors and fabricators running internal welding data platforms, automated inspection systems and welder qualification workflows.",
      stage: "Fabricate",
      needs: [
        "Standardized data exchange with EPCs & operators",
        "Less manual reporting and documentation effort",
        "Welding records integrated with materials & NDT data",
        "Demonstrable welding quality at project close-out",
      ],
      challenges: [
        "Welding data trapped inside internal systems",
        "Manual reporting to EPCs & operators per project",
        "Limited integration with material & inspection data",
        "Significant effort required to compile project documentation",
      ],
      value: [
        "Welding parameters & inspection results flow into the SMR automatically",
        "Standardized exchange with EPCs & operators, no rebuilding per project",
        "Welding records connected to upstream materials & downstream inspections",
        "Documentation workload replaced by data exchange",
        "Improved transparency for project stakeholders",
      ],
      content: [
        "Value for Welding Contractors",
        "Welding Data Integration",
        "Welder & WPS Qualification Records",
        "Connector / Plugin Documentation",
      ],
    },
    {
      code: "NDT",
      name: "Inspection & Testing Companies",
      short: "Inspection & Testing",
      who: "NDT service providers, AUT specialists, destructive & non-destructive testing labs and on-site inspection companies verifying materials, welds and coatings.",
      stage: "Verify",
      needs: [
        "Inspection results delivered as data, not just reports",
        "Integration with supplier & manufacturing records",
        "Less time spent on documentation & reporting",
        "Strong traceability across project stakeholders",
      ],
      challenges: [
        "Inspection findings still delivered as PDFs & report bundles",
        "Limited integration with supplier & manufacturing data",
        "Time-consuming documentation & report assembly",
        "Difficult traceability across multi-tier projects",
      ],
      value: [
        "NDT, AUT & lab results integrated directly into the SMR",
        "Real-time visibility for operators & EPCs on inspections",
        "Inspection approvals become digitally verified, immutable records",
        "Reduced documentation workload",
        "Stronger compliance & audit readiness across projects",
      ],
      content: [
        "Value for Inspection & Testing Companies",
        "NDT, AUT & Lab Data Integration",
        "Digital Inspection Approvals",
        "Third-Party Inspector Workflows",
      ],
    },
    {
      code: "EPC",
      name: "EPC Contractors (Onshore & Offshore)",
      short: "EPC Contractors",
      who: "Engineering, Procurement and Construction contractors coordinating pipeline construction: from spoolbases and fabrication yards to offshore installation vessels and third-party inspectors.",
      stage: "Construct",
      needs: [
        "On-time, on-budget project execution",
        "Efficient management of supplier documentation",
        "Continuous insight into supplier production quality",
        "Lower QA/QC workload during project close-out",
      ],
      challenges: [
        "Massive volumes of supplier docs to coordinate",
        "MRBs assembled manually after project completion",
        "Limited interoperability between contractor systems",
        "Operator demands for faster, cleaner handover packages",
      ],
      value: [
        "Automated, digital Manufacturing Record Books generated during production",
        "Real-time visibility into supplier quality data",
        "Integrates with welding, inspection and project QA platforms",
        "Less QA/QC effort & cleaner deliverables to the operator",
        "Improved transparency for pipeline operators",
      ],
      content: [
        "Value for EPC Contractors",
        "Digital MRB Capabilities",
        "Project Execution Use Cases",
        "Spoolbase & Offshore Vessel Integration",
      ],
    },
    {
      code: "OP",
      name: "Pipeline Operators (IOCs & NOCs)",
      short: "Pipeline Operators",
      who: "Asset owners building & operating onshore and offshore pipelines, LNG, petrochemical and energy-transition infrastructure (hydrogen, CCS, CO₂ transport). The market makers: they define the rules the supply chain adopts.",
      stage: "Operate",
      flag: "Market makers",
      needs: [
        "Confidence in supply-chain manufacturing quality",
        "Real-time visibility during construction, not after",
        "End-to-end traceability for regulators & integrity",
        "Trusted data foundation for Digital Twins & AI",
      ],
      challenges: [
        "Limited visibility into manufacturing quality during execution",
        "Documentation delivered months after completion",
        "Fragmented data across multiple supplier tiers",
        "Aging assets & tightening regulatory pressure (e.g. PHMSA 192/193/195)",
      ],
      value: [
        "Digital compliance documentation across the supply chain",
        "Automated verification and compliance by design",
        "Blockchain security, trust and auditability",
        "Faster transition from project execution to operations",
        "Lifecycle data foundation for integrity, AI & Digital Twins",
      ],
      content: [
        "Value for Operators",
        "Strategic Priorities of Energy Operators",
        "Hydrogen, CCS & Energy Transition Use Cases, AI Datacenters",
        "Tier-1 Pilot Case",
      ],
    },
  ];

  // STAKEHOLDER MATRIX — buyer personas inside operators & EPCs
  const PERSONAS = [
    {
      code: "EXEC",
      name: "Executive Leadership",
      short: "Executive Leadership",
      role: "Economic buyer",
      who: "VP / Director of Quality, Engineering, Operations, Asset Integrity & Reliability, and Supply Chain & Materials at IOCs, NOCs and tier-1 EPCs. Economic buyers and strategic sponsors.",
      needs: [
        "Protect CAPEX and reduce project execution risk",
        "Operate complex assets with leaner teams",
        "Enable enterprise digital, AI and Digital Twin agendas",
        "Preserve long-term asset value & license to operate",
      ],
      challenges: [
        "Project delays driven by documentation bottlenecks",
        "Managing operational and supply chain risk",
        "Aging workforce & knowledge drain",
        "Poor data quality blocking AI / Digital Twin initiatives",
        "Rising regulatory & traceability requirements",
      ],
      value: [
        "Compliance-by-design across the supply chain",
        "74% fewer NCRs & up to 60% less QA/QC effort (tier-1 pilot)",
        "Trusted data foundation for AI, analytics & Digital Twins",
        "Lifecycle traceability that protects residual asset value",
        "Reduce project execution risk",
        "Improve cost efficiency through automation",
        "Increase transparency across global supply chains",
      ],
      content: [
        "Executive Brief / Business Case",
        "Strategic Priorities of Energy Operators",
        "Tier-1 Operator Pilot Results",
        "ROI & Value Model",
      ],
    },
    {
      code: "QA/QC",
      name: "QA / QC Teams",
      short: "QA / QC Teams",
      role: "Primary daily user",
      who: "QA/QC managers, project QA/QC engineers, supplier quality leads and inspection coordinators. The primary daily users of SteelTrace.",
      needs: [
        "Verify supplier data against QCP / ITP requirements",
        "Catch NCRs early, before they impact installation",
        "Reduce time spent on document review",
        "Stay audit-ready at any moment",
      ],
      challenges: [
        "Manual review of mill certs, NDT reports, weld & coating records",
        "Late discovery of non-conformances",
        "Documentation arriving long after manufacturing",
        "Limited transparency across the supply chain",
        "Time-consuming audit preparation",
      ],
      value: [
        "Automated rule-based validation against QCP / ITP",
        "Real-time visibility into supplier quality data",
        "Immutable, blockchain-secured audit trail",
        "Reduced manual document review",
        "Earlier detection of NCRs",
        "Focus shifts from document chasing to engineering oversight",
      ],
      content: [
        "Smart Manufacturing Records Overview",
        "QCP / ITP Automation",
        "Sample Digital MRB",
        "Compliance-by-Design",
      ],
    },
    {
      code: "PM",
      name: "Project Management",
      short: "Project Management",
      role: "Budget owner",
      who: "Project managers, project engineering leads and project execution directors at operators and EPCs. Typically the budget owner. SteelTrace sits inside project CAPEX.",
      needs: [
        "On-time, on-budget delivery",
        "Predictable approval cycles across suppliers",
        "Real-time view of supplier manufacturing progress",
        "Single source of truth across contractors",
      ],
      challenges: [
        "Documentation delays blocking shipment & installation",
        "Coordinating QA/QC across multiple tiers of suppliers",
        "Late compliance issues triggering rework",
        "Information latency between stakeholders",
      ],
      value: [
        "Digital approval workflows that compress cycle times",
        "Earlier detection of compliance issues during production",
        "Real-time insight into supplier production and quality status",
        "All stakeholders working from the same verified data",
        "Faster mechanical completion & handover to operations",
        "Structured data makes documentation issues easier to resolve",
      ],
      content: [
        "Value Across the Pipeline Lifecycle",
        "Project Execution Use Cases",
        "Operator & EPC Pilot Case Studies",
        "FEED / FID Adoption Guide",
      ],
    },
    {
      code: "OPS",
      name: "Operations & Asset Integrity",
      short: "Operations & Integrity",
      role: "Long-term beneficiary",
      who: "Asset integrity engineers, reliability engineers, operations & maintenance leaders responsible for assets after handover. Long-term beneficiaries of SteelTrace data.",
      needs: [
        "Reliable manufacturing history for every component",
        "Faster root-cause analysis on incidents",
        "Higher-quality inputs to predictive maintenance models",
        "Extend asset lifetime & defer CAPEX",
      ],
      challenges: [
        "Manufacturing data trapped in PDFs & scanned MRBs",
        "Slow retrieval of original certs years after handover",
        "Incomplete traceability on critical components",
        "Hard to integrate with asset integrity systems",
      ],
      value: [
        "Instant access to verified manufacturing & inspection history",
        "Lifecycle traceability of materials, welds & coatings",
        "Better predictive maintenance models",
        "Structured data integrates with integrity & CMMS systems",
        "Verified residual value at end-of-life / decommissioning",
        "Integration with digital twins and asset systems",
      ],
      content: [
        "Asset Lifecycle Traceability",
        "Operational Value of SMRs",
        "Hidden Financial Value of Traceable Materials",
        "Decommissioning & Material Recovery",
      ],
    },
    {
      code: "DIG",
      name: "Digital Transformation",
      short: "Digital Transformation",
      role: "Strategic sponsor",
      who: "Digital transformation leads, IT / enterprise architecture, Digital Twin & data teams. Strategic sponsors who care about data foundations more than any one workflow.",
      needs: [
        "Structured, AI-ready data from manufacturing & QA/QC",
        "Integration with ERP, CMMS, EDMS & Digital Twin platforms",
        "Open APIs and no new data silos",
        "Enterprise-grade security & data ownership",
      ],
      challenges: [
        "AI & Digital Twin initiatives stalled by poor data quality",
        "Manufacturing data locked in PDFs & supplier portals",
        "Fragmented data across SCADA, SAP, EDMS & spreadsheets",
        "Building & maintaining homegrown solutions",
      ],
      value: [
        "Manufacturing & inspection data captured as structured datasets",
        "Open APIs & plugins for ERP, asset integrity, Digital Twin",
        "Blockchain-secured signatures (EAS / Ethereum L2)",
        "A shared data environment across manufacturers, inspectors & operators",
        "The supply-chain data layer the industry is missing",
      ],
      content: [
        "Platform Architecture & APIs",
        "Integrations & Plugins",
        "Security & Blockchain Infrastructure",
        "Digital Twin Enablement",
      ],
    },
    {
      code: "ENG",
      name: "Materials & Engineering",
      short: "Materials & Engineering",
      role: "Requirement owner",
      who: "Materials & metallurgy engineers, welding engineers, inspection engineers and field service coordinators. Technical experts who define and enforce requirements.",
      needs: [
        "Embed QCP / ITP requirements upfront",
        "Trustworthy material & process history",
        "Faster, deeper engineering reviews",
        "Preserve specialist knowledge as the workforce retires",
      ],
      challenges: [
        "Spec interpretation differs across suppliers",
        "Manual cross-checking of welds, NDT & mill data",
        "Engineering knowledge trapped in individuals & PDFs",
        "Limited reuse of data across projects",
      ],
      value: [
        "Requirements (QCP / ITP) embedded in the platform upfront",
        "Data captured at the source & auto-verified against specs",
        "Reusable engineering rules across projects and assets",
        "Structured records that survive personnel turnover",
      ],
      content: [
        "QCP / ITP Configuration",
        "Materials Traceability: Melt to End Product",
        "Welding & NDT Data Integration",
        "Engineering Knowledge Capture",
      ],
    },
  ];

  const COMMITMENTS = {
    segments:
      "Connecting the energy supply chain through Smart Manufacturing Records: verified data, end-to-end traceability, lifecycle value.",
    personas:
      "The standard for Smart Manufacturing Records in safety-critical industries: trusted data for safety, performance & capital efficiency.",
  };

  window.ST_DATA = { SEGMENTS, PERSONAS, COMMITMENTS };
})();
